#! /usr/bin/bash

set -e

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="rds-update-sg-rule"
printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"

export codespaces_IP=$(curl ifconfig.me)
export DB_SG_ID="sg-0a2f601a6a3c2a2b2"
export DB_SG_RULE_ID="sgr-0e863c98c7e6deaf7" 

echo "Codespaces public IP: $codespaces_IP"
echo "DB Security Group ID: $DB_SG_ID"
echo "DB Security Group RULE ID: $DB_SG_RULE_ID"

aws ec2 modify-security-group-rules \
    --group-id $DB_SG_ID \
    --security-group-rules "SecurityGroupRuleId=$DB_SG_RULE_ID,SecurityGroupRule={Description=codespaces,IpProtocol=tcp,FromPort=5432,ToPort=5432,CidrIpv4=$codespaces_IP/32}"