#! /usr/bin/bash
set -e # stop if it fails at any point

CYAN='\033[1;36m'
NO_COLOR='\033[0m'
LABEL="db-setup"
printf "${CYAN}==== ${LABEL}${NO_COLOR}\n"

script_path="$(realpath .)/script"

source "$script_path/db/drop"
source "$script_path/db/create"
source "$script_path/db/schema-load"
source "$script_path/db/seed"
python3 "$script_path/db/update-cognito-user-ids"